### PR TITLE
Do not write YAML tags to instance and bindings

### PR DESCRIPTION
**Pull request by felixzieger**
I try to solve https://github.com/meshcloud/unipipe-service-broker/issues/69. However, the the YAMLGenerator config option to disable types tagging inlines tags. For originatingIdentity, we end up with two platform keys, which makes the resulting the YAML invalid. Therefore this PR is marked as draft.

### CODE REVIEW

**Review by JohannesRudolph — COMMENTED** [review]
> for originatingIdentity, we end up with two platform keys, 

Not sure what you want to say with that. From the code in ServiceBinding.kt and ServiceInstance.kt it looks like unipipe broker simply "echos" whatever values it receives from the platform (marketplace) without performing any further validation. 

According to the OSB spec https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#originating-identity-header the `platform` value should be a proper platform identifier string like `cloudfoundry` or `meshmarketplace` (ref: 

our testdata which uses `null` and `http://localhost:8080/serviceRegistry/location/1` is wrong here - maybe that's the problem?

**Comment by DorukAkinci** [comment]
I believe we should wait this PR to release our next version. This is also important for the new credentials handling if users choose the terraform handlers for their service instances and bindings. Our most of users use terraform on their OSB. There is a hidden prerequisite(replacing these inline tags with bash script) at the moment if we cannot release it soon probably we should document that this is not a mandatory value and they can remove it safely from their yaml files to process them.

**Comment by felixzieger** [comment]
> > for originatingIdentity, we end up with two platform keys,
> 
> Not sure what you want to say with that. From the code in ServiceBinding.kt and ServiceInstance.kt it looks like unipipe broker simply "echos" whatever values it receives from the platform (marketplace) without performing any further validation.
> 
> According to the OSB spec https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#originating-identity-header the `platform` value should be a proper platform identifier string like `cloudfoundry` or `meshmarketplace` (ref:
> 
> our testdata which uses `null` and `http://localhost:8080/serviceRegistry/location/1` is wrong here - maybe that's the problem?

The problem is, that the platform key is shown twice in the output with the YAMLGenerator config I tried out.

image

**Comment by DorukAkinci** [comment]
I have figured out this happens when you use customised originatingIdentity at the moment. it is not about your change, the current version has the same issue as well. 

image

**Comment by DorukAkinci** [comment]
I have figured out this logic. Basically the model automatically puts the first parameter of the originatingIdentity header into the base64 json model. If you duplicate the value also in the base64 format then you see 2 lines for the same record. you can also set 2 different values if you pass different parameters in the header itself and base64. We should check our test cases. 

image

**Pull request closed without merging**
